### ISSUE TITLE
MyBookTable Rewrites Error

### ISSUE THREAD

**Issue by needtakehave** [authormedia/mybooktable#9] opened 2018-05-19 21:14 UTC
How do I fix this error?

`MyBookTable Rewrites Error – You have a plugin or theme that has post types or taxonomies that are conflicting with MyBookTable. MyBookTable pages will not display correctly.`

**Comment by WrStudio** [comment] 2018-09-26 22:48
I'm having the same problem, in an installation of this plugin on a wordpress site. I've already disabled all other plugins, and I've also changed my theme to a recommended theme on the plugin's developer page, but nothing worked. The error continues and the details pages of books, authors and series are not displayed, due to some taxonomy error.

**Comment by zookatron** [comment] 2018-09-27 02:05
This message is caused by mybooktable detecting that the paths it wants to use for books (e.g. www.yourdomain.com/books) are not properly being assigned to it's post types, which is usually caused by another plugin claiming those paths first.

If you're getting this message with no other plugins or non-default themes enabled, the only thing I can think of that could cause this is if you have some very strange permalink settings or something. I would double check that you are using a standard pretty permalinks setting in Settings > Permalinks on the WordPress admin menu.

**Closed** 2019-06-30 19:27 UTC
