### ISSUE TITLE
Template overrides not working

### ISSUE THREAD

**Issue by stormhillmedia** [authormedia/mybooktable#8] opened 2017-07-17 21:15 UTC
I moved templates to my theme as described here:
https://github.com/authormedia/mybooktable/wiki/Template-System-Overview

This does not seem to work. This is with pro3 version activated.

**Comment by zookatron** [comment] 2017-07-21 00:55
Apologies for the late reply, been abnormally busy with other work the past week.

I just ran a few tests and the template system seems to be working as intended.

Can you describe exactly what template you're attempting to override and how you have attempted to do so? If possible, emailing me a zip file of the theme folder with the templates in it that are not working would also be helpful.

**Comment by zookatron** [comment] 2017-08-16 21:17
Hi @stormhillmedia, any update on this?

**Comment by zookatron** [comment] 2017-09-06 18:05
Hi @stormhillmedia, I'm going to close this for now due to lack of reproducability, feel free to open it again if you have more details on how to reproduce the issues.

**Closed by zookatron** 2017-09-06 18:05 UTC
